# Generated by Django 6.0 on 2025-12-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassignedusername',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='grade',
            field=models.CharField(choices=[('A', 'A (85-100)'), ('B', 'B (70-84)'), ('C', 'C (55-69)'), ('D', 'D (40-54)'), ('F', 'F (Below 40)')], max_length=2),
        ),
    ]
