# Generated by Django 6.0 on 2025-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_preassignedusername_full_name_alter_transcript_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksreport',
            name='is_read_by_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportreply',
            name='is_read_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
