# Generated by Django 6.0.3 on 2026-03-08 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_marksreport_is_read_by_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department (for teachers)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Roll Number (for students)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, help_text='Section (for students, e.g., A, B)', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, help_text='Class (for students, e.g., Grade 10)', max_length=50),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_student', 'Created Student'), ('edit_student', 'Edited Student'), ('delete_student', 'Deleted Student'), ('create_teacher', 'Created Teacher'), ('edit_teacher', 'Edited Teacher'), ('delete_teacher', 'Deleted Teacher'), ('create_course', 'Created Course'), ('edit_course', 'Edited Course'), ('delete_course', 'Deleted Course'), ('bulk_import', 'Bulk Import'), ('bulk_email', 'Bulk Email Generation'), ('export_data', 'Exported Data'), ('other', 'Other Action')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
