# Generated by Django 6.0.3 on 2026-03-10 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_preassignedemail_delete_preassignedusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lectures/%Y/%m/')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('doc', 'Word Document'), ('image', 'Image'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the lecture')),
                ('is_published', models.BooleanField(default=True, help_text='Whether students can view this lecture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='main.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'order', '-created_at'],
            },
        ),
    ]
