# Generated by Django 6.0.3 on 2026-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_discussionthread_discussionreply_quiz_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', help_text='Section', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='student_class',
            field=models.CharField(choices=[('Prep', 'Prep'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', help_text='Class/Grade level', max_length=10),
        ),
    ]
