# Generated by Django 6.0.3 on 2026-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_section_course_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('alumni', 'Alumni')], default='active', help_text='User status (for students and record keeping)', max_length=20),
        ),
    ]
