# Generated by Django 6.0.3 on 2026-03-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('create_course', 'Created Course'), ('edit_course', 'Edited Course'), ('enroll_students', 'Enrolled Students'), ('upload_lecture', 'Uploaded Lecture'), ('create_assessment', 'Created Quiz/Test'), ('upload_transcript', 'Uploaded Transcript/Grade'), ('update_grades', 'Updated Student Grades'), ('post_report', 'Posted Report/Reply'), ('mark_attendance', 'Marked Attendance'), ('other', 'Other Academic Action')], max_length=50)),
                ('student_class', models.CharField(blank=True, max_length=20)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_activity_logs', to='main.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_logs', to='main.user')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeacherActivityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.teacheractivitylog')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_notifications', to='main.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('admin', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='TeacherActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('message', 'Message to Teacher'), ('report_question', 'Report/Question Activity')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_responses', to='main.user')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.teacheractivitynotification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
