# Generated by Django 6.0.3 on 2026-03-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_teacher_activity_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheractivityresponse',
            name='is_read_by_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
