# Generated by Django 6.0.3 on 2026-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_attendance_section_attendance_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_seen_by_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='seen_by_target_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
