# Generated by Django 6.0.3 on 2026-03-18 12:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auditlog_is_seen_by_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='checked_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_quiz_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='is_manually_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='manual_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('subjective', 'Subjective')], default='mcq', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='selected_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.CreateModel(
            name='TranscriptQuizMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attempt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_mark', to='main.quizattempt')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_marks', to='main.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_marks', to='main.quiz')),
            ],
            options={
                'ordering': ['-attempt_date'],
                'unique_together': {('enrollment', 'quiz')},
            },
        ),
    ]
