# Generated by Django 6.0.3 on 2026-03-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_quizanswer_answer_text_quizanswer_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_key_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_answer_keys/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_key_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_key_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='auto_submit_on_timeout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='omr_source_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_sources/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_display_mode',
            field=models.CharField(choices=[('full', 'Show Full Quiz'), ('one_by_one', 'Show One by One')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_source',
            field=models.CharField(choices=[('manual', 'Manual MCQ Entry'), ('omr_upload', 'Upload MCQ File (OMR Style)')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('auto', 'Auto-Graded (MCQs / OMR)'), ('manual', 'Manual (Subjective)')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto from Questions')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_answers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answers_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='obtained_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending_check', 'Pending Check')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('omr', 'OMR MCQ'), ('true_false', 'True/False'), ('subjective', 'Subjective')], default='mcq', max_length=20),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('result_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending Check')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='main.quizattempt')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
