# Generated by Django 6.0.3 on 2026-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_question_options_quiz_answer_key_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('auto', 'MCQ Only (Auto-Graded)'), ('manual', 'Subjective Only (Manual)'), ('mixed', 'Mixed Mode (MCQ + Subjective)')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending_review', 'Pending Review'), ('submitted_late', 'Submitted Late'), ('not_submitted', 'Not Submitted')], default='in_progress', max_length=20),
        ),
    ]
