# Generated by Django 6.0.3 on 2026-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_quiz_allow_late_submission_quizattempt_is_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='auto_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='auto_publish_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
