# Generated by Django 6.0.3 on 2026-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quiz_auto_publish_at_quiz_auto_publish_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
