# Generated by Django 6.0.3 on 2026-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_quiz_passing_marks_alter_quiz_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_file',
            field=models.FileField(blank=True, help_text='Upload question file (PDF, Image, Word, etc.)', null=True, upload_to='questions/%Y/%m/'),
        ),
    ]
