# Generated by Django 6.0.3 on 2026-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_question_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='paper_file',
            field=models.FileField(blank=True, help_text='Full question paper (PDF, Image, Word, Excel)', null=True, upload_to='quiz_papers/%Y/%m/'),
        ),
    ]
