# Generated by Django 6.0.3 on 2026-04-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_quiz_passing_marks_alter_quiz_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Quiz can be saved as draft and published later', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('auto', 'MCQ Only (Auto-Graded)'), ('manual', 'Subjective Only (Manual)'), ('mixed', 'Mixed (MCQ + Subjective)')], default='auto', max_length=20),
        ),
    ]
