# Generated by Django 6.0.3 on 2026-04-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_quiz_status_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('auto', 'MCQ Only (Auto-Graded)'), ('manual', 'Subjective Only (Manual)')], default='auto', max_length=20),
        ),
    ]
