# Generated by Django 6.0.3 on 2026-04-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_quiz_status_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='allow_late_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='auto_submit_on_timeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('auto', 'MCQ Only (Auto-Graded)'), ('manual', 'Subjective Only (Manual)'), ('mixed', 'Mixed Mode (MCQ + Subjective)')], default='auto', max_length=20),
        ),
    ]
