# Generated by Django 6.0.3 on 2026-04-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_assignmentsubmission_teacher_marks_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksreport',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.enrollment'),
        ),
        migrations.AddField(
            model_name='marksreport',
            name='issue_type',
            field=models.CharField(choices=[('marks', 'Marks Issue'), ('attendance', 'Attendance Issue'), ('general', 'General')], default='marks', max_length=20),
        ),
        migrations.AddField(
            model_name='marksreport',
            name='report_type',
            field=models.CharField(choices=[('student_report', 'Student Report'), ('teacher_message', 'Teacher Message')], default='student_report', max_length=20),
        ),
        migrations.AlterField(
            model_name='marksreport',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.transcript'),
        ),
    ]
